import type { TreeNode } from '../core/tree'
import { collectRoutes } from './collectPaths'

/**
 * Content of the generated `.d.ts` file that makes TypeScript understand the
 * virtual `unplugin-react-router/routes` module **and** exposes the typed
 * routing surface derived from the current page tree:
 *
 * - `AppRoutePath` — union of every route URL (autocomplete for links),
 * - `RouteParams<P>` — per-route param shape (feeds `useParams`),
 * - `RouteConfig` — the type of a page module's `export const route`,
 * - `LoaderData<T>` — convenience alias for loader return values.
 */
export function generateDTS(root: TreeNode): string {
  const routes = collectRoutes(root)

  const header = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-react-router. DO NOT MODIFY THIS FILE.
// Add this file to your tsconfig "include"/"files" entry if it is not picked
// up automatically (default tsconfigs often include every \`*.d.ts\` under root).
`

  const pathUnion = routes.map((r) => JSON.stringify(r.fullPath))
  const appRoutePath =
    pathUnion.length === 0
      ? `export type AppRoutePath = never`
      : `export type AppRoutePath =
${pathUnion.map((p) => `  | ${p}`).join('\n')}`

  const paramsEntries = routes.map((r) => {
    const shape =
      r.paramKeys.length === 0
        ? `Record<string, never>`
        : `{ ${r.paramKeys.map((k) => `${JSON.stringify(k)}: string`).join('; ')} }`
    return `  ${JSON.stringify(r.fullPath)}: ${shape}`
  })
  const appRouteParams =
    paramsEntries.length === 0
      ? `export interface AppRouteParams {}`
      : `export interface AppRouteParams {
${paramsEntries.join('\n')}
}`

  return `${header}
declare module 'unplugin-react-router/routes' {
  import type { RouteObject } from 'react-router'

  export const routes: RouteObject[]
  export default routes

  // ---- generated typed surface (from src/pages) ----
  ${appRoutePath}

  ${appRouteParams}

  /**
   * Params shape of a route path. Use it to type \`useParams\`:
   * \`\`\`ts
   * const { id } = useParams<RouteParams<'/users/:id'>>()
   * \`\`\`
   * Routes without params yield \`Record<string, never>\`.
   */
  export type RouteParams<P extends AppRoutePath> = P extends keyof AppRouteParams
    ? AppRouteParams[P]
    : Record<string, never>

  /**
   * Type of a page module's route-level overrides:
   * \`\`\`ts
   * // src/pages/users/[id].tsx
   * export const route = {
   *   path: '/member/:id',
   *   caseSensitive: true,
   *   handle: { crumb: 'User' },
   * } satisfies RouteConfig
   * \`\`\`
   */
  export interface RouteConfig {
    /** Override the URL derived from the file name (leaf page files only). */
    path?: string
    /** Make the generated route case sensitive. */
    caseSensitive?: boolean
    /** Static \`handle\` merged onto the generated route record. */
    handle?: unknown
  }

  /**
   * Convenience type for loader return values:
   * \`\`\`ts
   * const data = useLoaderData<LoaderData<typeof loader>>()
   * \`\`\`
   */
  export type LoaderData<T extends (...args: never[]) => unknown> = Awaited<
    ReturnType<T>
  >
}
`
}
