/**
 * Content of the generated `.d.ts` file that makes TypeScript understand the
 * virtual `unplugin-react-router/routes` module.
 */
export function generateDTS(): string {
  return `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-react-router. DO NOT MODIFY THIS FILE.
// Add this file to your tsconfig "include"/"files" entry if it is not picked
// up automatically (default tsconfigs often include every \`*.d.ts\` under root).

declare module 'unplugin-react-router/routes' {
  import type { RouteObject } from 'react-router'
  export const routes: RouteObject[]
  export default routes
}
`
}
